# Generated by Django 3.1.8 on 2021-04-28 18:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0022_auto_20180620_1551'),
        ('web_portal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Speciality',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='web_portal_speciality', serialize=False, to='cms.cmsplugin')),
                ('name', models.CharField(default='name', max_length=50)),
                ('short_description', models.CharField(default='short_description', max_length=100)),
                ('description', models.CharField(default='description', max_length=200)),
                ('footer', models.CharField(default='footer', max_length=50)),
                ('image', models.ImageField(upload_to='')),
                ('page', models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, related_name='related_page_link', to='cms.page')),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
        migrations.CreateModel(
            name='SpecialityList',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='web_portal_specialitylist', serialize=False, to='cms.cmsplugin')),
                ('list_title', models.CharField(default='list_title', max_length=50)),
                ('short_description', models.CharField(default='short_description', max_length=100)),
                ('description', models.CharField(default='description', max_length=200)),
                ('list', models.ManyToManyField(blank=True, to='web_portal.Speciality', verbose_name='Related List')),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
    ]
