# Generated by Django 3.1.8 on 2021-05-23 19:07

from django.db import migrations, models
import django


class Migration(migrations.Migration):

    dependencies = [
        ('web_portal', '0002_hello_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='PanoramaImage',
            fields=[
                ('cmsplugin_ptr',
                 models.OneToOneField(auto_created=True, on_delete=models.deletion.CASCADE, parent_link=True,
                                      primary_key=True, related_name='web_portal_panoramaimage', serialize=False,
                                      to='cms.cmsplugin')),
                ('name', models.CharField(default='name', max_length=50)),
                ('image', models.ImageField(upload_to='')),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
    ]
