# Generated by Django 3.1.8 on 2021-04-28 18:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0022_auto_20180620_1551'),
        ('web_portal', '0003_auto_20210429_0012'),
    ]

    operations = [
        migrations.RenameField(
            model_name='specialitylist',
            old_name='list',
            new_name='related_link',
        ),
        migrations.RemoveField(
            model_name='speciality',
            name='page',
        ),
        migrations.AddField(
            model_name='speciality',
            name='page_link',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='page_link', to='cms.page'),
        ),
    ]
